-- CREATE TABLE authors (
--     author_id SERIAL PRIMARY KEY,
--     fName VARCHAR(20),
--     lName VARCHAR(20),
--     bio VARCHAR(500),
--     imgPath VARCHAR
-- );

-- CREATE TABLE categories (
--     category_id SERIAL PRIMARY KEY,
--     category_name VARCHAR(30)
-- );

-- CREATE TABLE articles (
--     id SERIAL PRIMARY KEY,
--     title VARCHAR(50),
--     author_id INTEGER REFERENCES authors (id),
--     category INTEGER REFERENCES categories (id),
--     article_body VARCHAR,
--     publish_date DATE,
--     visible BOOLEAN
-- );

-- CREATE TABLE comments (
--     id SERIAL PRIMARY KEY,
--     username VARCHAR(30),
--     post_date DATE,
--     article_id INTEGER REFERENCES articles (id),
--     comment_body VARCHAR,
--     visible BOOLEAN
-- );